### ISSUE TITLE
plugin does not see playlists

### ISSUE THREAD

**Issue by ITguy3118** [june3474/script.slideshow-BGM#2]
So far this plugin is shaping up to be exactly what i have been looking for, but i'm unclear on using the playlists method. I made a slideshow playlist with my music and saved it. When i select playlist in the settings, i'm expected to navigate to the playlist?.....ok, but i thought it would find the playlist directory automagically. I located the playlist in '.\Kodi\portable_data\userdata\playlists\music\'  outside of kodi, but when i navigate to the folder, the folder is blank... Not sure if this is by design or not, but i have other playlists in that directory. I don't want it to play multiple different playlists, only a specific one. This design poses somewhat of an issue for me as I sync my config between multiple devices so i would need to be able to point to the default kodi directory recursively. 
Any help on this is appriciated...else good job on this so far, but need to either understand or fix it in a way that allows for the previous mentioning to take place.

**Comment by june3474** [comment]
Hi,
Yes, you need to navigate to the playlist.
As for the your playlist, what is the extension of the playlist files?
slideshow-bgm currently shows only .pls and .m3u files out of [6 playlist types](https://kodi.wiki/view/Basic_playlists) kodi supports.
But it is just not showing other types; showing them is quite simple and you will be able to easily find out where to modify if you look in the "settings.xml" file of the source; playing also would not be a problem, I guess.
The location of the playlist is not a problem either whether it is inside kodi or not.

Regarding the sync problem, settings of slideshow-bgm are saved "settings.xml"--this is different settings.xml from what is mentioned above--in  C:\Users\[username]\AppData\Roaming\Kodi\userdata\script.service.slideshow-bgm folder, presumably you are using Windows. So if your devices have the playlist on the same path, you can just copy the file instead of setting each device manually.

Cheers,

**Comment by ITguy3118** [comment]
Thanks for the reply, I added |*.xsp in the settings file under mask, and the playlist showed up, but i get an error now when running the slideshow . Can this not do smart playlists?
mask="*.pls|*.m3u|*.xsp" 

`
2022-02-18 16:43:47.392 T:98632   ERROR <general>: EXCEPTION: Not a valid playlist
2022-02-18 16:43:47.421 T:98632   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'RuntimeError'>
                                                   Error Contents: Not a valid playlist
                                                   Traceback (most recent call last):
                                                     File "D:\Kodi\Kodi\portable_data\addons\script.service.slideshow-bgm\addon.py", line 16, in <module>
                                                       player = Player()
                                                     File "D:\Kodi\Kodi\portable_data\addons\script.service.slideshow-bgm\resources\lib\player.py", line 22, in __init__
                                                       self.playlist = self.load_playlist()
                                                     File "D:\Kodi\Kodi\portable_data\addons\script.service.slideshow-bgm\resources\lib\player.py", line 64, in load_playlist
                                                       playlist.load(playlist_file)
                                                   RuntimeError: Not a valid playlist
                                                   -->End of Python script error report<--`

**Comment by june3474** [comment]
Could you post your playlist file? 
And does Kodi play the playlist in normal situation?

**Comment by june3474** [comment]
@ITguy3118 
I have look into the source code of Kodi.
It seems like Kodi does not consider .xsp file as a valid playlist file which it can creates PlayList object with.
Take a look at the [IsPlaylist() function](https://github.com/xbmc/xbmc/blob/master/xbmc/playlists/PlayListFactory.cpp) below.

`bool CPlayListFactory::IsPlaylist(const std::string& filename)
{
  return URIUtils::HasExtension(filename,
                     ".m3u|.b4s|.pls|.strm|.wpl|.asx|.ram|.url|.pxml|.xspf");
}`
FYI, .xspf is a totally different file format from Kodi's .xsp(smart playlist).

Anyhow, I'm working on the patch. I would like to suggest you to convert the .xsp playlist into .m3u for the time being.

**Comment by ITguy3118** [comment]
@june3474 i'm trying to use the path 'special://masterprofile/playlists/music/Acoustic Playlist.m3u' in the settings file as i have this set up in portable mode. I feel like this should work, but for some reason it's not. 

` 2022-03-18 09:20:09.892 T:75868    INFO <general>: [slideshow-bgm] Invalid playlist file: special://masterprofile/playlists/music/Acoustic Playlist.m3u
                                                   
2022-03-18 09:20:09.892 T:75868    INFO <general>: CPythonInvoker(64, D:\Kodi\Kodi\portable_data\addons\script.service.slideshow-bgm\addon.py): script aborted
2022-03-18 09:20:09.893 T:75868   ERROR <general>: Traceback (most recent call last):
                                                   
2022-03-18 09:20:09.893 T:75868   ERROR <general>:   File "D:\Kodi\Kodi\portable_data\addons\script.service.slideshow-bgm\addon.py", line 14, in <module>
                                                   
2022-03-18 09:20:09.893 T:75868   ERROR <general>:     
2022-03-18 09:20:09.893 T:75868   ERROR <general>: sys.exit()
2022-03-18 09:20:09.893 T:75868   ERROR <general>: 
                                                   
2022-03-18 09:20:09.893 T:75868   ERROR <general>: SystemExit
2022-03-18 09:20:09.893 T:75868   ERROR <general>: : 
2022-03-18 09:20:09.893 T:75868   ERROR <general>: 
2022-03-18 09:20:09.893 T:75868   ERROR <general>: 
`

**Comment by june3474** [comment]
This issue has been resolved in v0.4.0.
@ITguy3118 Thank you for your interest.
Pls try the v0.4.0 and feel free to open issues if any.
